# Generated by Django 4.2.3 on 2023-08-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm_password',
        ),
        migrations.AlterField(
            model_name='video',
            name='file_video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
