# Generated by Django 4.2.3 on 2023-09-07 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VideoAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
    ]
