# Generated by Django 4.2.3 on 2023-07-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file_video',
            field=models.CharField(max_length=100),
        ),
    ]
