# Generated by Django 4.2.3 on 2023-07-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoAPP', '0002_alter_video_file_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file_video',
            field=models.FileField(upload_to='media/'),
        ),
    ]
