# Generated by Django 4.2.3 on 2023-09-07 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VideoAPP', '0004_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
