# Generated by Django 4.2.3 on 2023-09-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoAPP', '0005_remove_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
