# Generated by Django 4.2.3 on 2023-09-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoAPP', '0007_customgroup_delete_company_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Administrador'), (0, 'Usuario')], null=True),
        ),
        migrations.DeleteModel(
            name='CustomGroup',
        ),
    ]
